### PR TITLE
rename Packet to Equinix Metal in docs

### PR DESCRIPTION
**Pull request by displague**
[Packet is now Equinix Metal!](https://blog.equinix.com/blog/2020/10/06/equinix-metal-metal-and-more/), keep an eye on this project for future resource name changes.

* rename Packet to Equinix Metal in docs

Does not affect k8s resource names, container image names, git repo or org names, or Crossplane package names.

Signed-off-by: Marques Johansson <mjohansson@equinix.com>

### Checklist

I have:
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Ensured this PR contains a neat, self documenting set of commits.
- [ ] Updated any relevant [documentation], [examples], or [release notes].
- [ ] Updated the [package resources documentation] and [`app.yaml`] to include any new managed resources or classes.

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplane/crossplane/tree/master/PendingReleaseNotes.md
[`app.yaml`]: https://github.com/packethost/crossplane-provider-packet/blob/master/config/package/manifests/app.yaml
[package resources documentation]: https://github.com/packethost/crossplane-provider-packet/blob/master/config/package/manifests/resources

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
LGTM, will follow up with any remaining changes 👍 are you planning to go ahead and rename repo?

**Comment by displague** [comment]
@hasheddan renamed to https://github.com/packethost/crossplane-provider-equinix-metal - let me know if the name is problematic.

**Comment by hasheddan** [comment]
@displague it is a little long, which probably isn't a huge deal, bu might be kind of cumbersome for docker image if we want to match. What would you think of something like `xp-provider-metal`? Images would be `equinix/xp-provider-metal` and `equinix/xp-provider-metal-controller`.

**Comment by displague** [comment]
Is Crossplane adopting the `xp` prefix elsewhere? The thing with these names is that you are generally not typing them in, so I'm not too worried about it. If the `xp` prefix is being adopted, I wouldn't mind renaming it.

**Comment by hasheddan** [comment]
@displague our on-disk package extension is `.xpkg`, so there is some precedence. There are also XRDs and XRs. I think the primary place that would be annoying for folks is with the `kubectl install provider equinix/crossplane-provider-equinix-metal:latest`

**Pull request merged**
